add tests for Block not downloaded error
noffle/kappa-osm pull request #21
Opened 2022-06-16 20:29 UTC by sethvincent

Could probably have a simpler test case but this serves as an example.

2022-06-16 21:09 UTC, gmaclennan commented
I'm not at my computer but does this replicate the same error we are seeing on bugsnag? I think what we are seeing is caused by the equivalent of sparse replication leaving a core with undownloaded blocks (because replication is non-linear so when it is interrupted it leaves the core sparse). I think to replicate that situation we need to replicate a core in sparse and download, say, only blocks 0,1,2,4,5, leaving 3 undownloaded.

2022-06-16 23:46 UTC, sethvincent commented
I revised things and it looks like the desired behavior of continued indexing does happen after this error as long as the error emitter is handled.

2022-06-20 10:07 UTC, gmaclennan commented
Great, so this should maybe be a passing test? "Indexing continues ignoring missing block" or something similar? It seems like there is no fix that needs made here.

2022-06-20 16:40 UTC, sethvincent commented
:+1: yeah, that seems right to me. i'll push a commit to make it pass.

2022-06-20 16:51 UTC, gmaclennan requested changes

2022-06-20 16:51 UTC, gmaclennan commented on .github/workflows/node.yml
> +    branches: [main]
```suggestion
    branches: [master]
```

2022-06-20 16:51 UTC, gmaclennan commented on .github/workflows/node.yml
> +    branches: [main]
```suggestion
    branches: [master]
```

2022-06-20 17:00 UTC, gmaclennan approved these changes

2022-06-20 18:39 UTC, merged